batch_size: 32
epochs: 50
augmentations: ['mix', 'erase', '']
label_smoothing: 0.1
model_file: models.resnet_flowers_planar
model_name: rn18_modified

checkpoint: ./checkpoints/1aap2q6c099.dict

wandb:
  project: flowers-planar
  name: resnet18-planar_

general:
  torchinfo_shape: [32,3,224,224]

dataset:
  train: /media/sergey/faq/flower_data_resized/train
  test: /media/sergey/faq/flower_data_resized/valid
  stats: [[0.485, 0.456, 0.406], [0.229, 0.224, 0.225]]
  crop: 224
  num_classes: 102